In [8]:
import numpy as np
import pandas as pd

In [31]:
l=np.array([1,2,3,4,5,6,7,8,9,10])
print(l)
type(l)

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [40]:
#if any value will float it will convert every value into flaot
#string then it will convert every value into string
k=[45,53,87,67,4.5]
np.array(k)


array([45. , 53. , 87. , 67. ,  4.5])

In [41]:
np.array([1,23,3,45,6,67,89])

array([ 1, 23,  3, 45,  6, 67, 89])

In [44]:
#np.arange() function
num=np.arange(1,100,2)
print(num)

np.arange(101,1,-1)



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


array([101, 100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,
        88,  87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,
        75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,
        62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,
        49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,
        36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,
        23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,
        10,   9,   8,   7,   6,   5,   4,   3,   2])

In [45]:
#mean() function
np.mean(num)

np.float64(50.0)

In [23]:
#std() function
np.std(num)

np.float64(28.861739379323623)

In [48]:
#np.random() function #randint  #randn
np.random.randint(1,100,30)    #start # end # numbers

array([25, 90, 22, 57, 49, 95, 42, 91, 78, 45, 71, 77, 85, 40, 38, 25, 63,
       83, 41, 41, 69, 91, 37, 69, 27, 34, 68,  5, 46, 49], dtype=int32)

In [51]:
np.random.randn(10)     #it give -3 to +3  random values 

array([-0.00766974, -1.42983931,  1.35963865, -0.94897824,  0.23412009,
       -0.02113746, -0.5740189 ,  2.51734652, -0.55547473,  0.27252487])

In [59]:
#np.linespace() function it partition into start value to end value as per partition number here is 5 
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [68]:
a1=np.array([[1,2,3],[4,5,6],[6,8,9]])
a1.ndim # to check dimensions

2

In [72]:
#eye identifer digonal
a2=np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
b=np.random.randn(5,5)
b

array([[-1.19729869,  0.33823943, -0.10997677, -0.48481849,  0.62629007],
       [-0.1382802 ,  3.04263123, -1.11831931, -1.49798062,  0.67774909],
       [-1.49863847, -1.23515312,  0.49545949, -1.14009704,  1.96572542],
       [ 0.29322148,  2.17494089,  1.90336487,  0.05617666,  2.14983883],
       [-0.94456704, -0.193841  ,  2.3720517 ,  0.58397757, -1.10135906]])

In [83]:
b.ndim

2

In [87]:
#reshape()
arr=np.random.randint(1,100,24)
arr


array([12, 26, 61, 17, 98, 92, 50, 98, 89, 23, 51, 84, 19, 74, 46, 84,  2,
       27, 95, 49, 96, 90, 48, 24], dtype=int32)

In [94]:
arr.reshape(8,3)
#arr.reshape(6,4)
#arr.reshape(4,6) #if 24 elements their then it always as like 6*4 or 4*6 

array([[12, 26, 61],
       [17, 98, 92],
       [50, 98, 89],
       [23, 51, 84],
       [19, 74, 46],
       [84,  2, 27],
       [95, 49, 96],
       [90, 48, 24]], dtype=int32)

In [96]:
np.max(a)

np.int64(99)

In [97]:
np.min(a)

np.int64(1)

In [100]:
data=np.random.randint(1,50,5)
data

array([ 3, 26, 27, 23,  9], dtype=int32)

In [102]:
np.sqrt(data)

array([1.73205081, 5.09901951, 5.19615242, 4.79583152, 3.        ])

In [103]:
np.mean(data)

np.float64(17.6)

In [105]:
np.sum(data)

np.int64(88)

In [106]:
np.exp(data)

array([2.00855369e+01, 1.95729609e+11, 5.32048241e+11, 9.74480345e+09,
       8.10308393e+03])

In [107]:
np.log(data)

array([1.09861229, 3.25809654, 3.29583687, 3.13549422, 2.19722458])

In [108]:
np.sin(data)

array([ 0.14112001,  0.76255845,  0.95637593, -0.8462204 ,  0.41211849])

In [109]:
np.cos(data)

array([-0.9899925 ,  0.64691932, -0.29213881, -0.53283302, -0.91113026])

In [110]:
np.sort(data)

array([ 3,  9, 23, 26, 27], dtype=int32)

In [111]:
np.average(data)

np.float64(17.6)

In [112]:
np.median(data)

np.float64(23.0)

In [114]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [118]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [119]:
np.abs(-6744)

np.int64(6744)

In [120]:
np.argmax(data)

np.int64(2)

In [121]:
np.argmin(data)

np.int64(0)

In [124]:
#nan for missing values
np.array([1,2,35,6,6,np.nan,765,4])


array([  1.,   2.,  35.,   6.,   6.,  nan, 765.,   4.])

In [136]:
ab1=12.43532
np.round(ab1,1)
#np.round(ab1,2)
#np.round(ab1,3)

np.float64(12.4)