 numpy
 

In [232]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [233]:
import numpy as np

In [234]:
print(np.__version__)

2.3.5


In [235]:
## creating arrays

In [236]:
list1=[1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [237]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3 4]


In [238]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [239]:
list1=[1,2,3,4]
list2=[5,6,7,8]
aee_list1_2=np.array([list1,list2])
print(aee_list1_2)

[[1 2 3 4]
 [5 6 7 8]]


In [240]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[8,9,10,11]
array_1_3=np.array([list1,list2,list3])
print(array_1_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]


In [241]:
# 2. numpy array attributes

In [242]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [243]:
print("shape",arr1.shape)
print("size",arr1.size)
print("dType",arr1.dtype)
print("n_dim",arr1.ndim)

shape (2, 3)
size 6
dType int64
n_dim 2


In [244]:
#practice create arrray and find its attributes

In [245]:
arr2=np.array([[1,2,3,4],[15,5,6,16],[7,8,9,18],[10,11,12,19]])
print(arr2)
print("shape",arr2.shape)
print("size",arr2.size)
print("dType",arr2.dtype)
print("n_dim",arr2.ndim)

[[ 1  2  3  4]
 [15  5  6 16]
 [ 7  8  9 18]
 [10 11 12 19]]
shape (4, 4)
size 16
dType int64
n_dim 2


In [246]:
#array intialixation method


In [247]:
#zero arrays
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [248]:
#one arrays
one_arr=np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [249]:
#full array
full_arr=np.full((3,2),7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [250]:
#identity matrix
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [251]:
#empty array
print(np.empty(2))

[9.9e-324 1.5e-323]


In [252]:
#evenly spaced array
print(np.arange(1,5,1))

[1 2 3 4]


In [253]:
#evenly spaced array
print(np.arange(1,10,1))  #1 is start #10 is end value #1 is step #10 will not include in that

[1 2 3 4 5 6 7 8 9]


In [254]:
#specific number of values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [255]:
#random values array # this is float
r_array=np.random.rand(3,2)
print(r_array)

[[0.65738706 0.92492521]
 [0.19847232 0.29743391]
 [0.35375948 0.58484451]]


In [256]:
#random values array -int
rint_array=np.random.randint(1,100,(3,3))
print(rint_array)

[[46 73 60]
 [68 13 67]
 [48 12 30]]


In [257]:
#array indexing and slicing

In [258]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [259]:
#index=0 1 2 3 4
#negative index= -5 -4 -3 -2 -1
#access individual characters in astring using their index.

In [260]:
print(a[0])   #indexing

print(a[1])
print(a[4])
print(a[-1])
print(a[-3])

1
3
9
9
5


In [261]:
#scliing
#array[start:stop:step]
#stop value  -index, that is not included in output

a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [262]:
#index=0 1 2 3 4
#negative index= -5 -4 -3 -2 -1
print(a[0:3]) #first 3 elements

[1 3 5]


In [263]:
print(a[-3:]) #last 3 elements
print(a[-2:]) #last 2 elements

[5 7 9]
[7 9]


In [264]:
print(a[1:4])  #middle 3 elements

[3 5 7]


In [1]:
print(a[0::2])   #with steps
print(a[0:4:2])
print(a)

NameError: name 'a' is not defined

In [266]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [267]:
print(arr2[0])   # its op prints one row [1,2,3]
print(arr2[1])   #its op prints second row [4,5,6]

[1 2 3]
[4 5 6]


In [268]:
print(arr2[0,0])   #-[0,0] means one row and its o idex value 0
print(arr2[1,0])   # [1,0] means second row and its index value 0

1
4


In [269]:
print(arr2[1])
print(arr2[1:])


[4 5 6]
[[4 5 6]]


In [270]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [271]:
print(arr2[:,0])

2D: [rowa,columns]
3D: [layers/height,rows,columns]

SyntaxError: invalid decimal literal (1885530762.py, line 3)

In [272]:
arr3=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr3)
print(type(arr3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [273]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [274]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [275]:
#slicing
print(arr3[:,0]) #1st column value
print(arr3[:,2]) #2nd column value

[1 4 7]
[3 6 9]


In [276]:
print(arr3[::,1:2]) #slicing on columns
print(arr3[2::,1:2]) #slicing on rows and columns


[[2]
 [5]
 [8]]
[[8]]


In [277]:
#array reshaping and flattening

In [278]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [279]:
reshaped=arr1.reshape((6,1))   #shape=1,5(1 rows & 5 columns) dimension=1
                               #shape=5,1(5 rows & 1 columns)  dimension=2
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [280]:
reshaped2=arr1.reshape((2,3))  #reshaping 2 dimensional array
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [281]:
#falatnning #it changes multilevel or higher dimension into one dimenssion array 
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [282]:
#array stacking and splitting

In [283]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.vstack((a,b))) #vertical stacking row-wise
print(np.hstack((a,b)))  #horizontal stacking column-wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [284]:
#splitting
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [285]:
split=np.hsplit(c,3)  #horizontal split 
for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [286]:
split=np.vsplit(c,2)  #vertical split 
for s in split:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [287]:
#mathematical operations on array

In [288]:
a=np.array([10,20,30,40,-30])
print(a)

[ 10  20  30  40 -30]


In [289]:
print(a+10) #add
print(a-30)  #sub
print(a*2)   #multiply
print(a/10)  #divide

[ 20  30  40  50 -20]
[-20 -10   0  10 -60]
[ 20  40  60  80 -60]
[ 1.  2.  3.  4. -3.]


In [290]:
b=np.array([1,4,9])
print(b)

[1 4 9]


In [291]:
print(np.square(b))  #square
print(np.sqrt(b))    #square root
print(np.sin(b))     #sin
print(np.tan(b))     #tan
print(np.cos(b))     #cos

[ 1 16 81]
[1. 2. 3.]
[ 0.84147098 -0.7568025   0.41211849]
[ 1.55740772  1.15782128 -0.45231566]
[ 0.54030231 -0.65364362 -0.91113026]


In [292]:
#mathematical operations on  multiple array

In [293]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a)
print(b)

[1 2 3]
[3 4 5]


In [294]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]


In [295]:
print(np.dot(a,b)) #3*1=3 + 2*4=8 + 3*5=15    =3+8+15=26   #dot product

26


In [296]:
#transpose it coverts row into coulmns
t=np.array([[1,2,3],[4,5,6]])
print(t) 
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [297]:
#statastical functions

In [298]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [299]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))

3.5
3.5
1.707825127659933
6
1


In [300]:
#array comparison

In [301]:
a=np.array([1,5,3])
b=np.array([4,5,6])
print(a)
print(b)


[1 5 3]
[4 5 6]


In [302]:
print(a ==b)    #compare each elements
print(np.array_equal(a,b))  #campairng complete array

[False  True False]
False


In [303]:
#handling with nan & inf

In [304]:
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


print(np.isnan(data1))

In [305]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]
