### 🧠 NumPy Practice Set (Strong Foundation)
### 🟢 LEVEL 1 — Core Basics (Must Master)

In [3]:
import numpy as np
l=[1,2,3,4,5,6,7,8,9]
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Create arrays of different dtypes (int, float, bool)
l=["vikas","patil"]
l
l=np.array(l)
l.dtype


dtype('<U5')

In [29]:
l=[1.1,1,2,34,5,5]
l=np.array(l)
l.dtype

dtype('float64')

In [33]:
l=[True,False,True]
l=np.array(l)
l.dtype


dtype('bool')

In [34]:
l.shape

(3,)

In [36]:
l.ndim

1

In [40]:
l.size

3

In [41]:
l.dtype

dtype('bool')

In [42]:
#Change dtype
import numpy as np

arr = np.array([1.1, 1, 2, 34, 5, 5])
arr.dtype


dtype('float64')

In [45]:
arr_int = arr.astype(int)
print(arr_int)
arr_int.dtype

[ 1  1  2 34  5  5]


dtype('int64')

In [49]:
#Using a 5×5 matrix:
arr = np.arange(25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
#Using a 5×5 matrix:
arr = arr.reshape(5, 5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
#Using a 5×5 matrix:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
#Extract rows   
#Correct NumPy indexing format
#✅ How to extract rows
#✔ First row
arr[0]



array([0, 1, 2, 3, 4])

In [63]:
#✔ Second row
arr[1]



array([5, 6, 7, 8, 9])

In [64]:
#✔ Last row
arr[-1]



array([20, 21, 22, 23, 24])

In [69]:
#✔ Multiple rows (rows 2–4)
a1=arr[1:4]
a1

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
import numpy as np

arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
#Extract columns
#Extract a single column
#🔹 First column
arr[:,0]

array([ 1,  6, 11, 16, 21])

In [80]:
#🔹 Second column
arr[:, 1]


array([ 2,  7, 12, 17, 22])

In [81]:
#🔹 Last column
arr[:, -1]




array([ 5, 10, 15, 20, 25])

In [82]:
#✅ Extract multiple columns
#🔹 Columns 2 to 4
arr[:, 1:4]


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [83]:

#✅ Keep column as 2D (important in ML)
arr[:, 1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [84]:
#Reverse the order of rows (top → bottom)
arr[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [86]:
#✅ Reverse columns (left ↔ right)
arr[:, ::-1]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [87]:
#Extract center element
arr[2, 2]



np.int64(13)

In [88]:
#Extract border elements
arr[0, :]


array([1, 2, 3, 4, 5])

In [90]:
#4️⃣ Reshaping
import numpy as np

arr = np.arange(1, 7)   # 1D array
print(arr)

import numpy as np

arr = np.arange(1, 7)   # 1D array
print(arr)


#Convert 2D → 1D
arr.reshape(2, 3)

#Flatten array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])




#Use reshape(-1) and explain why it works
arr.reshape(-1, 1)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [92]:
#dlatten array
arr.flatten()

array([1, 2, 3, 4, 5, 6])